### PR TITLE
Make underlineColorAndroid transparent by default

### PR DESCRIPTION
**Pull request by adamrainsby**

### CODE REVIEW

**Comment by adamrainsby** [comment]
@alvaromb Thoughts?

**Comment by alvaromb** [comment]
Sorry, super busy, I don't even have christmas holidays 😢 🎄 

Let me check...

**Comment by adamrainsby** [comment]
@alvaromb Thanks. I guess @gcanti needs to merge?

**Comment by gcanti** [comment]
Thanks @alvaromb for reviewing, I'll publish a new version asap

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-form-native/releases/tag/v0.6.2

**Comment by adamrainsby** [comment]
Thanks @gcanti

**Pull request merged**
