### PR TITLE
Set `accessibilityLabel` attributes on form controls, fix #137

### LINKED ISSUE #137: Set `accessibilityLabel` attributes on form controls
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.0
- react-native v0.22.2

### Expected behaviour

Tell us what should happen

As a blind developer, I should be able to hear my screen reader read the text labels associated with fields.

### Actual behaviour

Tell us what happens instead

Field labels aren't read, as seems to be indicated by the README should happen.

### Steps to reproduce

1. Launch TalkBack (or presumably VoiceOver.)
2. Use a form.
3. Touch a text field.

This can likely be solved by setting the `accessibleLabel` attribute on form controls to the text of their associated labels. Should be easy to do this programatically since you're generating the label already.

https://facebook.github.io/react-native/docs/accessibility.html

For bonus points, set up a live region for form validation errors on Android so they are read out automatically. :)

Thanks, love working with this library.

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

**Comment by gcanti** [comment]
I think, from my side, this is pretty much complete. Let me know if something isn't clear or needs furher details.

**Comment by alvaromb** [comment]
Looks good to merge @gcanti :rocket:

**Comment by gcanti** [comment]
👍

**Comment by tonychiu25** [comment]
@gcanti @alvaromb 
This commit does indeed attach an 'accessibilityLabel' to the tcomb-form components, but it is a bit restrictive because the 'accessibilityLabel' is simply set as the component's display label.

Since our automation test require heavily on the 'accessibilityLabel' as element selectors, using display labels, which may not be unique, isn't very viable -- as we cannot rely on display labels, which may contain duplicates, foreign languages... to function as unique element selectors. 

Would it possible to add a parameter in the options object that allows the caller to specify each component( textinput, datepicker ... )'s unique 'accessibilityLabel' as oppose to just using the display label value.

Thank you.

**Comment by AlanFoster** [comment]
+1 to your comment @tonychiu25 - running into the exact same issue. Specifically I don't wish to show a label for our login form, as I specify a placeholder value. In this scenario it would be good to explicitly set `accessibilityLabel`

@gcanti What are your thoughts on the following approach:

```diff
- accessibilityLabel={locals.label}
+ accessibilityLabel={locals.accessibilityLabel || locals.label}
```

**Pull request merged**
