### PR TITLE
Added collapsable iOS DatePicker

### PR DESCRIPTION
**Pull request by alvaromb**
@gcanti tests doesn't pass because `Animated` is undefined. Can you give me a hand to properly set up the test configuration?

### CODE REVIEW

**Comment by gcanti** [comment]
There are still some references to the `mockery` module, try to remove them (we don't need it anymore since we require `React` now):

https://github.com/gcanti/tcomb-form-native/blob/master/test/index.js#L3-L6

https://github.com/gcanti/tcomb-form-native/blob/master/test/index.js#L1123-L1124

**Comment by alvaromb** [comment]
I've just removed the `mockery` references. Now I'm getting this:

```
Error: Cannot find module 'ActivityIndicatorIOS'
```

**Comment by alvaromb** [comment]
It's strange because no `ActivityIndicatorIOS` is present in the actual source code...

**Comment by alvaromb** [comment]
I've just pushed the changes to show the test error.

**Comment by gcanti** [comment]
Ok, the culprit is this import in `components.js` I guess:

```js
const { Animated } = require('react-native');
```

RN is not listed in `devDependencies`, when the tests run it doesn't find the module

Requiring RN in `components.js` is absolutely necessary? Otherwise I'm afraid we should trash the tests.

**Comment by alvaromb** [comment]
Some state prop is needed in order to collapse the `DatePicker` element. If you want, I can try to substitute the animated to a simple `boolean`.

**Comment by gcanti** [comment]
> Some state prop is needed

I see. What about defining a statefull component inside `datepicker.ios.js`?

```js
import React from 'react';
import { Animated, View, TouchableOpacity, Text, DatePickerIOS } from 'react-native';

const UIPICKER_HEIGHT = 216;

class CollapsableDatePickerIOS extends React.Component {
  
  constructor(props) {
    super(props)
    this.state = {collapsedHeight: new Animated.Value(0)}
  }

  render() {
    const locals = this.props.locals
    <View>
      <TouchableOpacity onPress={() => {
          const currentHeight = locals._collapsedHeight._value;
          const height = (currentHeight === 0) ? UIPICKER_HEIGHT : 0;
          animation(locals._collapsedHeight, Object.assign({toValue: height}, animationConfig)).start();
        }}>
        <Text style={dateValueStyle}>
          {formattedValue}
        </Text>
      </TouchableOpacity>
      <Animated.View style={{height: locals._collapsedHeight, overflow: 'hidden'}}>
        <DatePickerIOS
          accessibilityLabel={locals.label}
          ref="input"
          maximumDate={locals.maximumDate}
          minimumDate={locals.minimumDate}
          minuteInterval={locals.minuteInterval}
          mode={locals.mode}
          timeZoneOffsetInMinutes={locals.timeZoneOffsetInMinutes}
          style={[datepickerStyle, {height: locals._collapsedHeight._value}]}
          onDateChange={(value) => locals.onChange(value)}
          date={locals.value}
        />
      </Animated.View>
    </View>
  }

}

function datepicker(locals) {
  if (locals.hidden) {
    return null;
  }

  const stylesheet = locals.stylesheet;
  let formGroupStyle = stylesheet.formGroup.normal;
  let controlLabelStyle = stylesheet.controlLabel.normal;
  let datepickerStyle = stylesheet.datepicker.normal;
  let helpBlockStyle = stylesheet.helpBlock.normal;
  let dateValueStyle = stylesheet.dateValue.normal;
  const errorBlockStyle = stylesheet.errorBlock;

  if (locals.hasError) {
    formGroupStyle = stylesheet.formGroup.error;
    controlLabelStyle = stylesheet.controlLabel.error;
    datepickerStyle = stylesheet.datepicker.error;
    helpBlockStyle = stylesheet.helpBlock.error;
    dateValueStyle = stylesheet.dateValue.error;
  }

  const label = locals.label ? <Text style={controlLabelStyle}>{locals.label}</Text> : null;
  const help = locals.help ? <Text style={helpBlockStyle}>{locals.help}</Text> : null;
  const error = locals.hasError && locals.error ? <Text accessibilityLiveRegion="polite" style={errorBlockStyle}>{locals.error}</Text> : null;

  let formattedValue = String(locals.value);
  let animation = Animated.timing;
  let animationConfig = {
    duration: 200
  };
  if (locals.config) {
    if (locals.config.format) {
      formattedValue = locals.config.format(locals.value);
    }
    if (locals.config.animation) {
      animation = locals.config.animation;
    }
    if (locals.config.animationConfig) {
      animationConfig = locals.config.animationConfig;
    }
  }

  return (
    <View style={formGroupStyle}>
      {label}
      <CollapsableDatePickerIOS locals={locals} />
      {help}
      {error}
    </View>
  );
}

module.exports = datepicker;
```

**Comment by alvaromb** [comment]
Yes, this is what we already have internally and it could solve the test issues (but I'm not sure because I'm no test expert in RN as you can see 😆). I didn't proposed this before because I wanted to maintain a more consistent code between the components.

If it looks good for you, I'll change it in a similar way that you propose.

**Comment by gcanti** [comment]
I think is ok. In general the `DatePicker` component in `components.js` should not change based on how you render the datepicker and every customisation should be defined in a template (unless you need more `options`). It's also how I'd integrate 3D party components.

**Comment by gcanti** [comment]
> RN is not listed in devDependencies, when the tests run it doesn't find the module

Out of curiosity... how the heck do people write tests for their components with RN???

**Comment by alvaromb** [comment]
I dunno, I haven't had time to dig deeper into tests yet.

**Comment by alvaromb** [comment]
There you go @gcanti. Now all tests pass and the animation state is encapsulated inside the collapsible component.

**Comment by alvaromb** [comment]
Now we should add something to the docs. At least expose the API that this component can handle (you can customize a few things with the `config` local).

**Comment by gcanti** [comment]
> Now we should add something to the docs. At least expose the API that this component can handle (you can customize a few things with the config local).

:+1:

Should we consider this a breaking change and bump the version to 0.6?

**Comment by alvaromb** [comment]
Well, it depends if you rely on the default date picker. I would work out of the box with the modified stylesheet but with a custom one you'll need to add a few values. My answer is "maybe yes".

**Comment by gcanti** [comment]
> My answer is "maybe yes"

When in doubt, I vote for bumping the version

**Comment by alvaromb** [comment]
So, let's bump it up! 💃

**Comment by alvaromb** [comment]
I think we lack a customization for the `TouchableOpacity` container, because I've just added the `dateValue` style object but it's not enough for most cases.

**Comment by alvaromb** [comment]
Now it's done. Can you take a quick look @gcanti and I'll add some info into the docs?

**Comment by alvaromb** [comment]
Also, we reached 1K ⭐'s!

🎉 🎈

**Comment by gcanti** [comment]
Looks good, thanks @alvaromb. Also, let's remove the `mockery` machinery, we don't need it anymore.

**Comment by alvaromb** [comment]
I prefer to do that on a separate PR if you don't mind.

**Comment by gcanti** [comment]
Sure, no problem 👍

**Comment by alvaromb** [comment]
Will try to add some docs today.

**Comment by alvaromb** [comment]
Hi @gcanti!

Cannot document this till' the next week. I expect to have some time on Monday, sorry 😢

**Comment by gcanti** [comment]
Hi @alvaromb,

never mind, I'm super busy as well (with a [babel plugin](https://github.com/gcanti/babel-plugin-tcomb) :sunglasses: )

**Comment by alvaromb** [comment]
@gcanti I've updated the `README`. I think this PR is finished and good to merge. Sorry for the delay!

**Comment by gcanti** [comment]
Thanks @alvaromb. Speaking about releases, before this I guess we should merge #173 since is v0.5.x compatible, release v0.5.2 and then merge this PR in order to release v0.6

**Comment by alvaromb** [comment]
Yes, this is a breaking change if you don't use the default stylesheet.

**Comment by alvaromb** [comment]
How do you feel about a collapsible `Picker`?

**Comment by gcanti** [comment]
Seems a good idea. In that case we should strive to group together all the breaking changes in the v0.6 release

**Comment by gcanti** [comment]
> Out of curiosity... how the heck do people write tests for their components with RN???

This seems interesting https://blog.formidable.com/unit-testing-react-native-with-mocha-and-enzyme-51518f13ba73#.p7zwc0n26

**Comment by alvaromb** [comment]
@gcanti FYI, I'm back! 

I'm going to implement the collapsible select tomorrow. Are we waiting for this to `0.6`? Is there anything else I can help you with?

**Comment by gcanti** [comment]
Hi @alvaromb, welcome back!

yes when you feel ready we can ship v0.6

**Comment by alvaromb** [comment]
@gcanti do you mind if I put the collapsible picker in this PR or you prefer me to open another one?

**Comment by gcanti** [comment]
@alvaromb ok for me, do what suits you better

**Comment by alvaromb** [comment]
There you go @gcanti!

**Comment by gcanti** [comment]
Thanks @alvaromb, going to merge this

**Comment by gcanti** [comment]
@alvaromb are you still working on something that will be included in v0.6 or we can ship the new release?

**Comment by alvaromb** [comment]
Would like to have some time to dig into the lists, I can't remember how that ended, but I do not have time to do it right now. I prefer to ship v0.6 now if you don't mind.

**Comment by gcanti** [comment]
Updated the change log, please double check it. If it's ok I'll release the new version asap

**Comment by alvaromb** [comment]
Completely right!

It's a breaking change because the stylesheet now requires some customization to both collapsible components.

🚀

**Comment by gcanti** [comment]
Released! Thanks again for your work on this

**Comment by code-h** [comment]
how can i set default value is empty ?

**Comment by Nygma297** [comment]
@gcanti @alvaromb  I'm new to this... How do i use it? is there some type of prop I need to use or is it collapsible by default???

**Pull request merged**
