### PR TITLE
Adds missing TextInput locals

### PR DESCRIPTION
**Pull request by alvaromb**

### CODE REVIEW

**Comment by alvaromb** [comment]
I have updated the `TextInput` locals to handle all the new props and removed deprecated ones.

**Comment by gcanti** [comment]
@alvaromb may I merge this?

**Comment by alvaromb** [comment]
Yes @gcanti!

Do you need further help/info?

**Comment by alvaromb** [comment]
We may lack another component props, but it's been pretty hectic here and I don't have time to look at it till' the next week 💀

**Comment by gcanti** [comment]
thx ;)

**Pull request merged**
