### PR TITLE
Added example for clearing form after submit

### PR DESCRIPTION
**Pull request by shashi-dokania**
While creating the form, it took me a while to figure out how to clear the form after submit since it was not documented explicitly. I think it would be a good idea to have it within the document.

### CODE REVIEW

**Comment by alvaromb** [comment]
Thanks for the PR @shashi-dokania!

@gcanti how do you feel about this?

**Comment by gcanti** [comment]
Hi @shashi-dokania, thanks for your PR.

> I think it would be a good idea to have it within the document

Agreed. But IMO the best way to clear a form is leveraging its controlled component nature:

https://github.com/gcanti/tcomb-form-native#adding-a-default-value-and-listen-to-changes

```js
var Person = t.struct({
  name: t.String,              // a required string
  surname: t.maybe(t.String),  // an optional string
  age: t.Number,               // a required number
  rememberMe: t.Boolean        // a boolean
});

var AwesomeProject = React.createClass({

  getInitialState() {
    return { value: null };
  },

  onChange(value) {
    this.setState({ value });
  },

  onPress() {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
      // clear the form only when values are valid
      // works for all inputs, checkboxes included
      this.setState({ value: null });
    }
  },

  render() {
    return (
      <View style={styles.container}>
        <t.form.Form
          ref="form"
          type={Person}
          value={this.state.value}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
});
```

**Comment by shashi-dokania** [comment]
@gcanti @alvaromb Thanks for the review. I have made changes based on your inputs and have also tested the changes in my app. Looks good.

**Comment by gcanti** [comment]
Looks good, thanks @shashi-dokania. Could you please squash your commits (the old ones are invalid and with a misleading description now)

**Comment by shashi-dokania** [comment]
Thanks @gcanti. I just squashed all my old commits.

**Comment by gcanti** [comment]
Great! Thanks a lot @shashi-dokania

**Comment by shashi-dokania** [comment]
Thank you very much @gcanti :)

**Pull request merged**
