### PR TITLE
refs #56 Transform enums keys 

### PR DESCRIPTION
**Pull request by alvaromb**
to ensure matching between different types. Issue: https://github.com/gcanti/tcomb-form-native/issues/56

### CODE REVIEW

**Comment by alvaromb** [comment]
All tests pass, let me know if you want me to add some tests for this use-case.

**Comment by gcanti** [comment]
Thanks, let me know when you want to release this

**Comment by alvaromb** [comment]
Feel free to make a minor release anytime you want :rocket:

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-form-native/releases/tag/v0.3.2

**Pull request merged**
