### PR TITLE
Solves the horizontal padding issue with text fields in Android

### PR DESCRIPTION
**Pull request by danilvalov**
Related issue: #327

### CODE REVIEW

**Comment by danilvalov** [comment]
@alvaromb 
This PR fixes [your changes](https://github.com/gcanti/tcomb-form-native/pull/325). Please, check it and tell me about any problems. We need to find a better way to solve issues #301 and #329.

**Comment by alvaromb** [comment]
Oh, I see, didn't noticed about the `paddingHorizontal`/`padding` change.

The better way to solve these issues is to make the community more active into the project. Thanks for contributing, @danilvalov.

**Comment by alvaromb** [comment]
@gcanti horizontal padding is coming back to the stylesheet. Good to merge.

**Comment by gcanti** [comment]
@alvaromb should I release a patch?

**Comment by alvaromb** [comment]
Yes, a patch would be ok. People extending base stylesheet could be affected by #325.

**Comment by gcanti** [comment]
Patch released

**Pull request merged**
