### PR TITLE
Default datepicker value

### PR DESCRIPTION
**Pull request by alvaromb**
Added support for avoiding an always default date in Date pickers.

### CODE REVIEW

**Comment by alvaromb** [comment]
@gcanti here you have a bunch of changes to support a non date default value for Date pickers, requested by some folks a while ago.

Also, `yarn.lock` should be checked in into the repo, as per Yarn docs: https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control

**Comment by alvaromb** [comment]
Updated docs and fixed Travis CI.

**Comment by alvaromb** [comment]
Will merge tomorrow and I'll ping you @gcanti to do the release. Also, if @javiercr can take a peek into this, it would be awesome.

Thanks!

**Comment by gcanti** [comment]
@alvaromb just added you as a maintainer on npm, you should be able to publish new releases

**Comment by alvaromb** [comment]
Cool m8, thanks!

**Comment by alvaromb** [comment]
Released: https://github.com/gcanti/tcomb-form-native/releases/tag/v0.6.12

**Pull request merged**
