### PR TITLE
Improved README for the custom stylesheets

### PR DESCRIPTION
**Pull request by alvaromb**
There's a bit of commit madness in this PR, sorry for that. I tried to squash all the things, but once you've pushed your stuff it becomes quite difficult to do. Anyway, I've improved a bit the form customisation documentation.

### CODE REVIEW

**Comment by gcanti** [comment]
> but once you've pushed your stuff it becomes quite difficult to do

maybe rebasing your branch?

**Comment by alvaromb** [comment]
Well, that's what I did. I rebased ``master`` on my fork. I always forget to branch when I change only the readme file and I put the changes on master, sorry.

I'm keeping your changes so the only thing that's going to be different are my doc updates, but if you don't want to merge this I'll reset my fork and start again, no problem :smile:

**Comment by gcanti** [comment]
Never mind, it's ok

**Comment by alvaromb** [comment]
Just FYI, I just did a hard reset to be completely synced with your code so I'll avoid this kind of errors on the next PR.

**Pull request merged**
