### PR TITLE
Append missing locals

### PR DESCRIPTION
**Pull request by zvona**
Appends missing local properties for Textbox.

### CODE REVIEW

**Comment by alvaromb** [comment]
Looks good, but some of the properties are platform-only. As long as the user reads the React Native docs, there's no problem by defining an Android prop and then running into iOS, it won't have any effect.

**Comment by zvona** [comment]
This was originally added for support of `maxLength` property, but then I discovered these platform specific properties are missing too. They're not necessary in this case, but I wanted to keep this PR consistent.

**Comment by alvaromb** [comment]
Yes, it looks good and it's great to have support for this Android props :)

@gcanti let me know if I can help you with the merge.

**Comment by gcanti** [comment]
@alvaromb I added you to the collaborator list, you should be able to merge / handle the repo now

**Comment by alvaromb** [comment]
@zvona would you mind to add this new props to the ``README.md`` file?

I think that they should also be in the [templates.js](https://github.com/gcanti/tcomb-form-native/blob/365c0e618df1d98317ed14c50a68b8e2245ba0cd/lib/templates/bootstrap.js) file, because otherwise I don't think that the React Native component it's going to get those props unless you define your own templates, am I right @gcanti?

**Comment by gcanti** [comment]
> am I right @gcanti?

Yep!

**Comment by zvona** [comment]
I updated the bootstrap.js template for TextInput. However, I'm not sure what information I should update on README.

**Comment by alvaromb** [comment]
Now it looks good and the tests pass :shipit:

**Comment by gcanti** [comment]
Thanks @zvona :+1:

**Pull request merged**
