### PR TITLE
Feature: Wrap TextInput in a View for More Customizable Styling

### PR DESCRIPTION
**Pull request by kenleezle**
This makes material design styling of textboxes achievable through stylesheets.

Without this, you must implement a template to render a textbox with an underline.*

This will allow customization of the border.

The reason this is necessary is because in React Native the TextInput component does not respect these granular border style declarations, they currently are recommending wrapping the TextInput in a View.

Related Issue: #37 

\* assuming you want the error to be under the underline

### CODE REVIEW

**Comment by kenleezle** [comment]
Just noticed this pr which does the same exact thing, doh: https://github.com/gcanti/tcomb-form-native/pull/259

@alvaromb

**Comment by kenleezle** [comment]
if you like this i can write up documentation complete with a screenshot for it, just wanted to see if this is something you would accept first.

**Comment by alvaromb** [comment]
@kenleezle previous PR need some changes, feel free to continue with this one. And yes, we could accept this.

**Comment by kenleezle** [comment]
ok @alvaromb afaik all that needs to be added to this PR is documentation including a screenshot. please lmk if you would like any additional modifications. I will work on the docs.

**Comment by kenleezle** [comment]
@alvaromb i updated the docs with an example and a screenshot. please let me know if there is anything else i can do.

**Comment by kenleezle** [comment]
@alvaromb happy holidays. please let me know if there is anything else that needs to be done for this pr. thanks! 🎄 🎆 🕎

**Comment by alvaromb** [comment]
Happy holidays @kenleezle!

I'm at the office right now, I'll try to find some time to review it today. Thanks!

**Comment by kenleezle** [comment]
@alvaromb bump, please let me know if you want any additional changes.

**Comment by gcanti** [comment]
Thanks @kenleezle @alvaromb. Should I release a new version after merging?

**Comment by alvaromb** [comment]
@gcanti yes!

I bet some people will need to change their custom stylesheet when updating, just FYI. Maybe not a minor version?

**Comment by gcanti** [comment]
Is there a way to make these changes backward compatible? Perhaps having a default for the new `stylesheet.textboxView` value?

**Comment by alvaromb** [comment]
If the user just clones the `stylesheet` it should be backwards compatible because there is already an empty default value of `textboxView`. If you just have copied and pasted the default stylesheet, you will need to update it by hand.

**Comment by kenleezle** [comment]
@gcanti here is the default definition for the new styles:

```js
textboxView: {
  normal: {
  },  
  error: {
  },  
  notEditable: {
  }
}
```

**Comment by gcanti** [comment]
I mean, stylesheets (namely their structure) are kind of public APIs, maybe we should try to avoid brecking changes for all users, even those which:

> If you just have copied and pasted the default stylesheet, you will need to update it by hand

**Pull request merged**
