### PR TITLE
0.3.1

### LINKED ISSUE #43: add support for nested forms

### PR DESCRIPTION
**Pull request by gcanti**
Hi @alvaromb,

This is a big refactoring. Basically I'd like to port some tcomb-form features, let me know if it makes sense and if you have comments / suggestions

Temporary changelog:

## v0.3.1

- **New Feature**
    - default templates are now split in standalone files, so you can cherry pick which ones to load
    - ability to customize templates, stylesheets and i18n without loading the default ones (improved docs)
    - porting of tcomb-form `getValidationErrorMessage` feature

    ```js
    var Age = t.refinement(t.Number, function (n) { return n >= 18; });

    // if you define a getValidationErrorMessage function, it will be called on validation errors
    Age.getValidationErrorMessage = function (value) {
      return 'bad age ' + value;
    };

    var Schema = t.struct({
      age: Age
    });
    ```

    - add support for nested forms, fix #43
        - add proper support for struct refinements
        - add support for struct label (bootstrap templates)

        **Example**

        ```js
        var Account = t.struct({
          email: t.String,
          profile: t.struct({
            name: t.String,
            surname: t.String
          })
        });

        var options = {
          label: <Text style={{fontSize: 30}}>Account</Text>,
          fields: {
            profile: {
              label: <Text style={{fontSize: 20}}>Profile</Text>
            }
          }
        };
        ```

        - add support for struct error (bootstrap templates)
- **Experimental**
    - add support for maybe structs

    **Example**

    ```js
    var Account = t.struct({
      email: t.String,
      profile: t.maybe(t.struct({
        name: t.String,
        surname: t.String
      }))
    });

    // user enters email: 'aaa', => result { email: 'aaa', profile: null }
    // user enters email: 'aaa', name: 'bbb' => validation error for surname
    // user enters email: 'aaa', name: 'bbb', surname: 'ccc' => result { email: 'aaa', profile: { name: 'bbb', surname: 'ccc' } }
    ```

### CODE REVIEW

**Comment by gcanti** [comment]
> This is a big refactoring

though completely backward compatible

**Comment by gcanti** [comment]
ops... fat finger on Close and comment...

**Comment by alvaromb** [comment]
I'll have some time to take a look into this tomorrow, sorry for the delay.

**Comment by gcanti** [comment]
Sure, take your time, and thanks again for your help

**Comment by alvaromb** [comment]
Expect a review tomorrow afternoon. I'm about to have a child and I'm navigating between the office, home and the hospital :baby: :baby_bottle:

**Comment by gcanti** [comment]
Wow! 

Congratulazioni!

**Comment by alvaromb** [comment]
@gcanti the PR looks great! Checked the code and everything seems ok. I've also tested your branch into one of my projects and it's running perfectly.

:shipit: :rocket:

**Comment by gcanti** [comment]
Great! Thanks for the review, do I proceed with the merge?

**Comment by alvaromb** [comment]
Sure!

**Pull request merged**
