### PR TITLE
Android date and time pickers

### PR DESCRIPTION
**Pull request by alvaromb**
Support for Android ``DatePickerAndroid`` and ``TimePickerAndroid``.

### CODE REVIEW

**Comment by alvaromb** [comment]
I can see some rebase hell over there, sorry @gcanti I should have created another branch :goberserk: . Let me know if you want me to create another and send the PR again.

**Comment by gcanti** [comment]
Wow, what's happened? What about squashing all the commits into one?

**Comment by alvaromb** [comment]
I tried to rebase and squash the commits, but they didn't show up running ``git rebase -i HEAD~10``. I'm not a rebase expert, so if you have some advice about how to deal with this (those commits are mostly from merges) I would be more than happy to learn something new and try to solve this commit madness.

If we can't solve this, I'll send another PR and close this one.

**Comment by alvaromb** [comment]
Never mind, I'm sending a new PR. Sorry for the inconveniences.

**Comment by alvaromb** [comment]
There you go! https://github.com/gcanti/tcomb-form-native/pull/122 :rocket:

**Pull request closed without merging**
