### PR TITLE
fixes #60 Adds support for Switch into Android.

### LINKED ISSUE #60: SwitchIOS is not supported n this Platform
Hey what about Android any plans about this ?

### PR DESCRIPTION
**Pull request by alvaromb**
Fixes https://github.com/gcanti/tcomb-form-native/issues/60.

``react-native`` dependency must be set to >=0.13.0.

### CODE REVIEW

**Comment by alvaromb** [comment]
@gcanti good to merge?

**Comment by gcanti** [comment]
mmh... I think this PR is invalid now:

- my commit (c6cfedad6dbcfde92f7134c4dad2761c56f5ffe3) is already on master
- your change to package.json is invalidated by d15c2b100968240ca5e2b1b8566985a48d4f5d68

Only the change SwitchIOS -> Switch seems still valid, right?

**Comment by alvaromb** [comment]
Yes, probably @gcanti. Tried to squash all the things but it's hard to do it once you've pushed changes. I'll send another PR.

**Comment by alvaromb** [comment]
I think now it's right @gcanti

**Comment by gcanti** [comment]
excelente

**Comment by alvaromb** [comment]
I managed to get through interactive rebase madness :godmode:

**Comment by alvaromb** [comment]
Just a quick reminder, we have to check that the ``package.json`` version gets updated @gcanti.

**Comment by gcanti** [comment]
Ok, thanks. Should I release a v0.4?

**Comment by alvaromb** [comment]
I wouldn't release v0.4 until https://github.com/gcanti/tcomb-form-native/issues/67 lands. I will be working on that tomorrow, so if you want to wait for the release it's ok for me.

**Comment by gcanti** [comment]
:+1:

**Pull request merged**
